### ISSUE TITLE
How to resolve json_encode with cp1251?

### ISSUE THREAD

**Issue by projct1** [Luracast/Laravel-Database#14]
Hello, my project charset is cp1251.

```php
$settings = [
    'driver'    => 'mysql',
    'host'      => $configDb['host'],
    'database'  => $configDb['name'],
    'username'  => $configDb['user'],
    'password'  => $configDb['pass'],
    'charset'   => 'cp1251',
    'collation' => 'cp1251_general_ci'
];

$connFactory = new ConnectionFactory(new Container);
$resolver = new ConnectionResolver;
$resolver->addConnection('mysql', $connFactory->make($settings));
$resolver->setDefaultConnection('mysql');

Model::setConnectionResolver($resolver);
```

All is ok, but `Models\BarTag::all()->toJson()` return false :(

How i can solve it?

**Comment by Arul-** [comment]
Looks like you are handling things directly like using Capsule. Here you should configure using a structure similar to Laraval

You set the database settings using config/datasbase.php see [database.php](https://github.com/Luracast/Laravel-Database/blob/master/config/database.php)

**Comment by projct1** [comment]
@Arul- tell me plz, how i can init this library with non-laravel project, using your config database.php?

**Comment by Arul-** [comment]
just follow the readme to create a project from scratch and
edit the `config/database.php` and edit the *mysql* config to use 

    'charset'   => 'cp1251',
    'collation' => 'cp1251_general_ci'

**Comment by projct1** [comment]
I deleted all previous code.
Here my `index.php`
```php
require '../vendor/autoload.php';
require '../vendor/laravel/database/bootstrap/autoload.php';

//trying to call any model
Models\Bar::find(1);
```
But got error: `Fatal error: Uncaught Error: Call to a member function connection() on null in D:\OpenServer\domains\gdebar\vendor\illuminate\database\Eloquent\Model.php:1253`

**Comment by Arul-** [comment]
Restart again with this repo unzipped and then make the changes to `config/database.php` as above and follow the README to create the example API. That should work

Once that works you can go ahead further

**Comment by projct1** [comment]
I.e. i have to download archive? Not install from composer?

**Comment by Arul-** [comment]
Either way is fine

**Comment by projct1** [comment]
I reinstall package from composer and replaced wrong path to original autoloader in file `vendor/laravel/database/bootstrap/autoload.php` from `require BASE . '/vendor/autoload.php` to `require BASE . '/../../autoload.php'`.

Now `DB::table('bars')` works fine, but when i call `Models/Bar::find(1)` i got error `Call to a member function connection() on null in .../gdebar\vendor\illuminate\database\Eloquent\Model.php`.

How i can set `DB::connection()` for all models?

**Comment by projct1** [comment]
I found this method:

```php
$resolver = new ConnectionResolver([
    'mysql' => DB::connection('mysql')
]);

$resolver->setDefaultConnection('mysql');

Model::setConnectionResolver($resolver);
```

Its ok? Or maybe can do it simpler or shorter?
