### ISSUE TITLE
Laravel-Database and Restler Framework Upgrade Question

### ISSUE THREAD

**Issue by abhishek70** [Luracast/Laravel-Database#8]
Hi @Arul- ,

Is there any plans for upgrading Laravel-Database from 5.2.* version and Restler Framework from 3.0.0-RC6 version?

Thank you,
Abhishek

**Comment by Arul-** [comment]
Since it's not tied to any version of Restler, you should be able to use any restler version.

For Laravel upgrade, what is the version you are looking for? are you ok to use older structure followed in this repository or follow Laravel conventions?

**Comment by abhishek70** [comment]
Currently I'm using Laravel-Database 5.2.* with this repository and wanted to use 5.8 as per Laravel current stable version and follow Laravel conventions if possible.

For Restler I'm currently using 3.0.0-RC6 version. Would there be any new releases for Restler?

**Comment by Arul-** [comment]
https://github.com/Arul-/reactive-restler will soon become restler 4

**Comment by abhishek70** [comment]
Restler 4 looks great. Will try soon with my project. Also please let me know if possible to upgrade this repository with Laravel-Database 5.8 with Laravel conventions?

**Comment by Arul-** [comment]
I will work on 5.8 upgrades in my spare time. Now I have more things on my
plate!

**Comment by abhishek70** [comment]
Sure. No problem. Thank you @Arul- .
