### ISSUE TITLE
Upgraded the Laravel-Database to 5.8.*

### ISSUE THREAD

**Issue by abhishek70** [Luracast/Laravel-Database#9]
Hi @Arul- ,

I was able to upgrade the Laravel-Database to 5.8.* by keeping the current folder structure same. I have tested on my end and its working as expected.

Whenever you have a chance can you please take a look at the changes : [https://github.com/abhishek70/Laravel-Database/tree/Laravel-Database-5.8](url)
and provide your feedback and suggestions regarding any changes.

If you want I can also create a pull request if that helps.

Thank you,
Abhishek

**Comment by Arul-** [comment]
Can you make a pull request here, I will test and approve it

**Comment by abhishek70** [comment]
Sure. Thanks

**Comment by Arul-** [comment]
Fixed in https://github.com/Luracast/Laravel-Database/pull/10

**Comment by Arul-** [comment]
I have also upgraded https://github.com/Luracast/Restler-Application with your contribution :)

**Comment by Arul-** [comment]
Now `_ide_helper.php` is the only file that is out of date!

**Comment by abhishek70** [comment]
> Now `_ide_helper.php` is the only file that is out of date!

Yeah. I will take a look at generating it using [https://github.com/barryvdh/laravel-ide-helper](url).

**Comment by Arul-** [comment]
https://github.com/barryvdh/laravel-ide-helper/issues/756 will help

**Comment by Arul-** [comment]
I just added IDE Helper support :)

I did it as a *thank you for your contribution!*

I had to include queue and files otherwise it was creating so many issues so I added them under dev requirements

**Comment by abhishek70** [comment]
Great. I will the pull the changes into my branch. Thank you @Arul- .

**Comment by Arul-** [comment]
As a bonus now we have the queue also available lazy loaded!
